name: Dispatch Acme Install Test

on:
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Install acme.sh
        run: |
          curl https://get.acme.sh | sh -s email=admin@zerocmf.com
