name: Dispatch Node Test

on:
  workflow_dispatch:

env:
  NODE_VERSION: '20'

jobs:
  ping:
    runs-on: ubuntu-latest
    environment: PRODUCTION
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: node -v
